"""Description of the migration

Revision ID: 1d280da1b09d
Revises: f6d4a6fb88d0
Create Date: 2024-04-03 16:04:46.497125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d280da1b09d'
down_revision: Union[str, None] = 'f6d4a6fb88d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('county', sa.String(), nullable=True))
    op.drop_constraint('users_full_name_key', 'users', type_='unique')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_full_name_key', 'users', ['full_name'])
    op.drop_column('users', 'county')
    # ### end Alembic commands ###
