"""Announcements model modification

Revision ID: 577769a35de6
Revises: ad336916e64c
Create Date: 2024-04-03 17:22:59.275805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577769a35de6'
down_revision: Union[str, None] = 'ad336916e64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('motor_capacity', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('fuel_type', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('gearbox', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('car_body', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('seats', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('horsepower', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('color', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('condition', sa.String(), nullable=True))
    op.alter_column('model', 'title',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'title',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('announcements', 'condition')
    op.drop_column('announcements', 'color')
    op.drop_column('announcements', 'horsepower')
    op.drop_column('announcements', 'seats')
    op.drop_column('announcements', 'car_body')
    op.drop_column('announcements', 'gearbox')
    op.drop_column('announcements', 'fuel_type')
    op.drop_column('announcements', 'motor_capacity')
    # ### end Alembic commands ###
