"""initial migration

Revision ID: 7c592ec73e62
Revises: d6d3d1eeb9d8
Create Date: 2024-04-18 15:17:42.336679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c592ec73e62'
down_revision: Union[str, None] = 'd6d3d1eeb9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_title', table_name='model')
    op.drop_table('model')
    op.drop_table('seller_ratings')
    op.drop_table('favorites')
    op.drop_index('ix_announcements_title', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_make_title', table_name='make')
    op.drop_table('make')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('make',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('title', name='make_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_make_title', 'make', ['title'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('announcements_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('additional_features', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('motor_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gearbox', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('car_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('horsepower', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='announcements_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='announcements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_announcements_title', 'announcements', ['title'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='favorites_announcement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_table('seller_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='seller_ratings_seller_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='seller_ratings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='seller_ratings_pkey')
    )
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('make_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['make.title'], name='model_make_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_pkey')
    )
    op.create_index('ix_model_title', 'model', ['title'], unique=False)
    # ### end Alembic commands ###
