"""Tabele make si model

Revision ID: ad336916e64c
Revises: 1d280da1b09d
Create Date: 2024-04-03 16:24:47.641320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad336916e64c'
down_revision: Union[str, None] = '1d280da1b09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make',
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_index(op.f('ix_make_title'), 'make', ['title'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['make.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_title'), 'model', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_title'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_make_title'), table_name='make')
    op.drop_table('make')
    # ### end Alembic commands ###
